//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GermanxChino {
	using System;
	
	
	/// <summary>
	///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
	/// </summary>
	// StronglyTypedResourceBuilder generó automáticamente esta clase
	// a través de una herramienta como ResGen o Visual Studio.
	// Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
	// con la opción /str o recompile su proyecto de VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Imagenes {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Imagenes() {
		}
		
		/// <summary>
		///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GermanxChino.Imagenes", typeof(Imagenes).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
		///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Circunferencia {
			get {
				object obj = ResourceManager.GetObject("Circunferencia", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Cuadrado {
			get {
				object obj = ResourceManager.GetObject("Cuadrado", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Cubo {
			get {
				object obj = ResourceManager.GetObject("Cubo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Esfera {
			get {
				object obj = ResourceManager.GetObject("Esfera", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Piramide {
			get {
				object obj = ResourceManager.GetObject("Piramide", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Rectangulo {
			get {
				object obj = ResourceManager.GetObject("Rectangulo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Trapecio {
			get {
				object obj = ResourceManager.GetObject("Trapecio", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Triangulo {
			get {
				object obj = ResourceManager.GetObject("Triangulo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
